#Server port
server:
  port: 8889
#application name
spring:
  application:
    name: GATEWAY-SERVICE
#  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"
#it is a client and a gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka